definitions:
  handler.pingResp:
    properties:
      status:
        type: string
    type: object
info:
  contact: {}
paths:
  /ping/{name}:
    get:
      description: very very friendly response
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.pingResp'
      summary: Show hello text
      tags:
      - Tests
swagger: "2.0"
